#!/bin/bash

set -eux

RUN_NODE_WITH_CDT_CMD="docker run --rm -v "$PWD":/daobet.contracts -w /daobet.contracts -ti daobot/daobet:node-with-cdt"

cmd="${1:?}"
shift

case "$cmd" in
(build) eval "$RUN_NODE_WITH_CDT_CMD" ./cicd/build.sh ;;
(test)  eval "$RUN_NODE_WITH_CDT_CMD" ./build/tests/unit_test "$@" ;;
(pack)  eval "$RUN_NODE_WITH_CDT_CMD" ./cicd/pack.sh ;;
(login) eval "$RUN_NODE_WITH_CDT_CMD" bash ;;
(*)     echo >&2 "Invalid command: $cmd." ; exit 1 ;;
esac
